[package]
name = "calibright_cli"
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
version = "0.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
calibright = "0.1"
env_logger = { version = "0.10" }
log = { workspace = true }

[dependencies.clap]
version = "4.0"
features = ["derive"]

[dependencies.tokio]
workspace = true
features = ["macros", "rt-multi-thread"]
